image: docker:latest
services:
- docker:dind
variables:
  DOCKER_DRIVER: overlay
  GROUP: midnight-lizard
  PROJ: ingress

gce-deploy:
  image: google/cloud-sdk
  stage: deploy
  only:
  - master
  script:
  - chmod +x ./shell/gcloud-config.sh
  - chmod +x ./shell/helm-deploy.sh
  - ./shell/gcloud-config.sh -k "$GCE_KEY" -z $GCE_CLUSTER_ZONE -p $GCE_PROJECT -c $GCE_CLUSTER_NAME
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - ./shell/helm-deploy.sh -r $PROJ -c ./kube/$PROJ