apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ml-tls-cert
spec:
  secretName: ml-tls-cert
  dnsNames:
    - midnight-lizard.org
  acme:
    config:
    - http01:
        ingress: ml-ingress
      domains:
        - midnight-lizard.org
        - '*.midnight-lizard.org'
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer