name: ml-ingress
annotations:
  kubernetes.io/ingress.global-static-ip-name: ml-static-ip
  ingress.kubernetes.io/rewrite-target: /
  kubernetes.io/ingress.class: "gce"
defaultBackend:
  serviceName: portal
  servicePort: 80
rules:
  "midnight-lizard.org":
    portal:
      path: /*
      port: 80
    schemes-commander:
      path: /schemes/commander/*
      port: 80
    schemes-querier:
      path: /schemes/querier/*
      port: 80
    impressions-commander:
      path: /impressions/commander/*
      port: 80
  "identity.midnight-lizard.org":
    identity:
      path: /*
      port: 80
tls:
  - hosts:
    - midnight-lizard.org
    secretName: ml-tls-cert-portal
  - hosts:
    - identity.midnight-lizard.org
    secretName: ml-tls-cert-identity