name: ml-ingress
enabled: true
defaultBackend:
  serviceName: portal
  servicePort: 80
rules:
  portal:
    "midnight-lizard.org": 80
    "*.midnight-lizard.org": 80
  identity:
    "identity.midnight-lizard.org": 80
  schemes-querier:
    "schemes-querier.midnight-lizard.org": 80
  schemes-commander:
    "schemes-commander.midnight-lizard.org": 80
annotations:
  kubernetes.io/ingress.global-static-ip-name: ml-static-ip
  ingress.kubernetes.io/rewrite-target: /
  certmanager.k8s.io/issuer: "letsencrypt-staging"
  certmanager.k8s.io/acme-challenge-type: http01
tls:
  - secretName: ml-tls
    hosts:
      - midnight-lizard.org
      - www.midnight-lizard.org
      - identity.midnight-lizard.org
      - schemes-querier.midnight-lizard.org
      - schemes-commander.midnight-lizard.org