name: ml-ingress
enabled: true
defaultBackend:
  serviceName: portal
  servicePort: 80
rules:
  portal:
    "midnight-lizard.org": 80
    "*.midnight-lizard.org": 80
  identity:
    "identity.midnight-lizard.org": 80
  schemes-querier:
    "schemes-querier.midnight-lizard.org": 80
  schemes-commander:
    "schemes-commander.midnight-lizard.org": 80
annotations:
  kubernetes.io/ingress.global-static-ip-name: ml-static-ip
  ingress.kubernetes.io/rewrite-target: /
tls:
  # Secrets must be manually created in the namespace.
  # - secretName: chart-example-tls
  #   hosts:
  #     - chart-example.local